package com.carcast.mirror

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

val LocalArabic = compositionLocalOf { false }

private val arabicTranslations = mapOf(
    "Cast" to "البث",
    "Cast screen" to "شاشة البث",
    "Receive" to "الاستقبال",
    "Browser" to "المتصفح",
    "Car" to "السيارة",
    "Help" to "المساعدة",
    "Settings" to "الإعدادات",
    "Diagnostics" to "التشخيص",
    "Confirm pairing code" to "تأكيد رمز الاقتران",
    "Pairing code" to "رمز الاقتران",
    "Continue" to "متابعة",
    "Cancel" to "إلغاء",
    "Local network access" to "الوصول إلى الشبكة المحلية",
    "Allow local network access" to "السماح بالوصول إلى الشبكة المحلية",
    "Nearby displays" to "الشاشات القريبة",
    "No displays found yet" to "لم يتم العثور على شاشات بعد",
    "Use Android System Cast" to "استخدام بث نظام Android",
    "Browser receiver" to "مستقبل المتصفح",
    "Start Browser Receiver" to "بدء مستقبل المتصفح",
    "Stop Casting" to "إيقاف البث",
    "Reconnect" to "إعادة الاتصال",
    "Approve this TV connection" to "الموافقة على اتصال التلفاز",
    "Approve & Start" to "موافقة وبدء",
    "Reject" to "رفض",
    "Open on your TV" to "افتح على التلفاز",
    "Car mode" to "وضع السيارة",
    "Help & FAQ" to "المساعدة والأسئلة الشائعة",
    "Privacy" to "الخصوصية",
    "Privacy options" to "خيارات الخصوصية",
    "Advertising" to "الإعلانات",
    "Language" to "اللغة",
    "English" to "الإنجليزية",
    "Arabic" to "العربية",
    "Arabic language" to "اللغة العربية",
    "Diagnostics" to "التشخيص",
    "Connection" to "الاتصال",
    "Video" to "الفيديو",
    "Network" to "الشبكة",
    "Audio" to "الصوت",
    "Manual receiver" to "مستقبل يدوي",
    "IP address" to "عنوان IP",
    "Port" to "المنفذ",
    "Start receiver" to "بدء المستقبل",
    "Stop receiver" to "إيقاف المستقبل",
    "Reduce lag" to "تقليل التأخير",
    "Try lower-resolution Smooth mode to reduce processing and network load. The image may be less sharp; this applies to your next cast." to "جرّب وضع السلاسة بدقة أقل لتقليل عبء المعالجة والشبكة. قد تصبح الصورة أقل وضوحاً؛ يطبق ذلك في البث التالي.",
    "Full screen" to "ملء الشاشة",
    "Exit full screen" to "إنهاء ملء الشاشة",
    "CONNECT" to "اتصال",
    "DECLINE" to "رفض",
    "CLEAR" to "مسح",
    "COPY DEBUG REPORT" to "نسخ تقرير التشخيص",
    "What will be shared" to "ما سيتم مشاركته",
    "Share device audio" to "مشاركة صوت الجهاز",
    "Actual stream" to "البث الفعلي",
    "Supported paths" to "المسارات المدعومة",
    "Why can’t I see a receiver?" to "لماذا لا أرى مستقبلاً؟",
    "Why is audio unavailable?" to "لماذا الصوت غير متاح؟",
    "How do I recover a failed session?" to "كيف أستعيد جلسة فاشلة؟",
    "What does CarCast store?" to "ماذا يخزن CarCast؟",
    "Cast screen" to "شاشة البث",
    "Find your display" to "ابحث عن شاشتك",
    "Securely mirror to a nearby screen on your local network." to "اعكس الشاشة بأمان إلى شاشة قريبة على شبكتك المحلية.",
    "PERMISSION NEEDED" to "الإذن مطلوب",
    "CarCast needs local network access to discover and securely connect to a receiver. Screen content is not uploaded." to "يحتاج CarCast إلى الوصول للشبكة المحلية للعثور على مستقبل والاتصال به بأمان. لا يتم رفع محتوى الشاشة.",
    "Scan again" to "إعادة الفحص",
    "Scan for displays" to "البحث عن الشاشات",
    "Keep this screen open while CarCast checks your local network. You can also connect by IP or use Android System Cast." to "أبقِ هذه الشاشة مفتوحة أثناء فحص CarCast لشبكتك المحلية. يمكنك أيضاً الاتصال بعنوان IP أو استخدام بث نظام Android.",
    "SCANNING" to "جارٍ الفحص",
    "FOUND" to "تم العثور",
    "TV" to "تلفاز",
    "CarCast Receiver" to "مستقبل CarCast",
    "APPROVAL REQUIRED" to "الموافقة مطلوبة",
    "Confirm that both screens show the same verification code:" to "تأكد من ظهور رمز التحقق نفسه على الشاشتين:",
    "Enter this code on the sender phone when prompted." to "أدخل هذا الرمز على هاتف الإرسال عند طلبه.",
    "Connected · " to "متصل · ",
    "STARTING" to "جارٍ البدء",
    "Starting Browser Receiver…" to "جارٍ بدء مستقبل المتصفح…",
    "Starting…" to "جارٍ البدء…",
    "NEEDS ATTENTION" to "يتطلب الانتباه",
    "FAILED" to "فشل",
    "حاول الضغط على بدء المستقبل مرة أخرى." to "حاول الضغط على بدء المستقبل مرة أخرى.",
    "ACTION REQUIRED" to "إجراء مطلوب",
    "Browser session" to "جلسة المتصفح",
    "Quality: " to "الجودة: ",
    "Waiting for browser" to "بانتظار المتصفح",
    "Send supported phone audio to the receiver." to "إرسال صوت الهاتف المدعوم إلى المستقبل.",
    "Stop Receiver" to "إيقاف المستقبل",
    "COMPATIBILITY NOTE" to "ملاحظة التوافق",
    "Browser receiver debug" to "تشخيص مستقبل المتصفح",
    "Last successful stage" to "آخر مرحلة ناجحة",
    "Last error stage" to "آخر مرحلة بها خطأ",
    "Exception" to "الاستثناء",
    "Message" to "الرسالة",
    "Unavailable" to "غير متاح",
    "None" to "لا يوجد",
    "LOCAL" to "محلي",
    "SECURE LOCAL CASTING" to "البث المحلي الآمن",
    "CarCast Debug Report" to "تقرير تشخيص CarCast",
    "Enter the temporary six-digit code shown on the receiver." to "أدخل الرمز المؤقت المكوّن من ستة أرقام الظاهر على المستقبل.",

    "CarCast needs local network access to discover and securely connect to a receiver. Screen content is not uploaded." to "يحتاج كاركاست إلى الوصول للشبكة المحلية للعثور على مستقبل والاتصال به بأمان. لا يتم رفع محتوى الشاشة.",
    "Keep this screen open while CarCast checks your local network. You can also connect by IP or use Android System Cast." to "أبقِ هذه الشاشة مفتوحة أثناء فحص كاركاست لشبكتك المحلية. يمكنك أيضاً الاتصال بعنوان IP أو استخدام بث نظام Android.",
    "CarCast Receiver · Available on local network" to "مستقبل كاركاست · متاح على الشبكة المحلية",
    "MEDIA ONLY — not full-screen mirroring" to "وسائط فقط — لا يدعم عكس الشاشة بالكامل",
    "Secure approval required on receiver" to "تتطلب الموافقة الآمنة على المستقبل",
    "Keep the phone and receiver on the same Wi-Fi network. Start the receiver first, then scan again. VPNs, guest Wi-Fi isolation, and captive portals can block local discovery." to "أبقِ الهاتف والمستقبل على شبكة Wi-Fi نفسها. ابدأ المستقبل أولاً ثم أعد الفحص. قد تمنع شبكات VPN أو عزل شبكة الضيوف أو صفحات تسجيل الدخول اكتشاف الأجهزة محلياً.",
    "Android playback capture supports eligible media and game audio only. Protected content, DRM-restricted apps, microphone input, and some manufacturer audio paths cannot be captured. Turn off Share device audio to continue video-only." to "يدعم التقاط التشغيل في Android الوسائط المؤهلة وصوت الألعاب فقط. لا يمكن التقاط المحتوى المحمي أو التطبيقات المقيدة بـ DRM أو إدخال الميكروفون أو بعض مسارات الصوت الخاصة بالشركات المصنّعة. عطّل مشاركة صوت الجهاز للمتابعة بالفيديو فقط.",
    "Stop the receiver, close the TV browser tab, reopen the displayed local URL, and start a new session. Each screen-share approval is single-use by Android design." to "أوقف المستقبل، وأغلق علامة تبويب المتصفح على التلفاز، ثم افتح الرابط المحلي الظاهر وابدأ جلسة جديدة. كل موافقة على مشاركة الشاشة تُستخدم مرة واحدة وفق تصميم Android.",
    "CarCast has no account, cloud relay, advertising SDK, or analytics service. Session diagnostics stay in app-private storage until you clear them; media stays on the local connection." to "لا يملك كاركاست حساباً أو مرحّلاً سحابياً أو خدمة تحليلات. تبقى تشخيصات الجلسة في مساحة التطبيق الخاصة حتى تمسحها، وتبقى الوسائط على الاتصال المحلي.",
    "The TV browser is ready. Approve now to start screen sharing immediately." to "متصفح التلفاز جاهز. وافق الآن لبدء مشاركة الشاشة فوراً.",
    "When you approve, CarCast captures your device screen and, if enabled, supported playback audio. It sends the stream only over the encrypted local connection to the receiver you approve; it is not uploaded or stored by CarCast." to "عند الموافقة، يلتقط كاركاست شاشة جهازك، وإذا فعّلت ذلك يلتقط صوت التشغيل المدعوم. يرسل البث عبر الاتصال المحلي المشفّر فقط إلى المستقبل الذي وافقت عليه، ولا يتم رفعه أو تخزينه بواسطة كاركاست.",
    "Factory Android Auto displays are not generic screen receivers. CarCast cannot bypass Android Auto or inject arbitrary phone pixels into a vehicle factory display." to "شاشات Android Auto المثبتة من المصنع ليست مستقبلات عامة للشاشة. لا يستطيع كاركاست تجاوز Android Auto أو إدخال محتوى شاشة الهاتف إلى شاشة المركبة الأصلية.",
    "Android-powered head unit with CarCast Receiver installed directly." to "وحدة تشغيل تعمل بنظام Android ومثبت عليها مستقبل كاركاست مباشرةً.",
    "Android Automotive OS only through an eligible, reviewed parked-app category." to "نظام Android Automotive OS فقط من خلال فئة تطبيقات متوقفة مؤهلة وخاضعة للمراجعة.",
    "External Miracast or receiver hardware using Android\'s public system handoff." to "جهاز Miracast خارجي أو عتاد استقبال يستخدم آلية النقل العامة في Android.",
    "Review or change the advertising privacy choices provided by Google\'s consent platform." to "راجع أو غيّر خيارات خصوصية الإعلانات التي توفرها منصة موافقة Google.",
    "Advertising privacy options are not currently required for this device or region." to "خيارات خصوصية الإعلانات غير مطلوبة حالياً لهذا الجهاز أو المنطقة.",
    "Limited banner ads may appear only on idle device screens. Ads are disabled during casting, receiver mode, approvals, and permission flows." to "قد تظهر إعلانات شريطية محدودة على شاشات الجهاز غير النشطة فقط. تُعطّل الإعلانات أثناء البث ووضع الاستقبال والموافقات وطلبات الأذونات.",
    "Ads are unavailable or not configured. Casting does not depend on advertising." to "الإعلانات غير متاحة أو غير مهيأة. لا يعتمد البث على الإعلانات.",
    "Previous CarCast session crashed." to "تعطلت جلسة كاركاست السابقة.",
    "Couldn’t connect" to "تعذر الاتصال",
    "Connection lost" to "انقطع الاتصال",
    "Try reconnecting to the TV browser." to "حاول إعادة الاتصال بمتصفح التلفاز.",
    "Starting…" to "جارٍ البدء…",
    "Browser receiver QR" to "رمز QR لمستقبل المتصفح",
    "Connection" to "الاتصال",
    "Video" to "الفيديو",
    "Network" to "الشبكة",
    "Audio" to "الصوت",
    "Protocol" to "البروتوكول",
    "State" to "الحالة",
    "Receiver" to "المستقبل",
    "Codec" to "الترميز",
    "Capture resolution" to "دقة الالتقاط",
    "Sent resolution" to "الدقة المرسلة",
    "FPS" to "الإطارات/ثانية",
    "Encoded FPS" to "الإطارات المشفّرة/ثانية",
    "Quality limitation" to "قيد الجودة",
    "Bitrate" to "معدل البت",
    "Bytes/sec" to "بايت/ثانية",
    "Frames sent" to "الإطارات المرسلة",
    "ICE state" to "حالة ICE",
    "Selected candidate pair" to "زوج المرشحين المحدد",
    "Local candidate type" to "نوع المرشح المحلي",
    "Remote candidate type" to "نوع المرشح البعيد",
    "RTT" to "زمن الاستجابة",
    "Packets lost" to "الحزم المفقودة",
    "Available outgoing bitrate" to "معدل البت الصادر المتاح",
    "Audio track" to "مسار الصوت",
    "Audio source" to "مصدر الصوت",
    "Audio codec" to "ترميز الصوت",
    "Audio sample rate" to "معدل عينات الصوت",
    "Audio channels" to "قنوات الصوت",
    "Audio bytes sent" to "بايتات الصوت المرسلة",
    "Audio packets sent" to "حزم الصوت المرسلة",
    "Browser UA" to "تعريف المتصفح",
    "LAN address" to "عنوان الشبكة المحلية",
    "Last successful stage" to "آخر مرحلة ناجحة",
    "Last error stage" to "آخر مرحلة بها خطأ",
    "Exception" to "الاستثناء",
    "Message" to "الرسالة",
    "Missing" to "مفقود",
    "None reported" to "لم يتم الإبلاغ عن شيء",
    "None" to "لا يوجد",
    "Unavailable" to "غير متاح",
    "Waiting for browser" to "بانتظار المتصفح",
    "Ready to receive from a nearby CarCast phone." to "جاهز للاستقبال من هاتف CarCast قريب.",
    "Stream to a TV or computer browser over your local network." to "بث إلى تلفاز أو متصفح كمبيوتر عبر شبكتك المحلية.",
    "Understand which in-vehicle paths CarCast supports." to "تعرّف على طرق الاستخدام التي يدعمها CarCast داخل المركبة.",
    "Private, local casting with clear recovery steps." to "بث محلي وخاص مع خطوات واضحة للاستعادة.",
    "Manage privacy choices without changing your casting setup." to "إدارة خيارات الخصوصية دون تغيير إعدادات البث.",
    "Session health and browser receiver troubleshooting." to "حالة الجلسة واستكشاف أخطاء مستقبل المتصفح وإصلاحها.",
    "Auto" to "تلقائي",
    "Smooth" to "سلس",
    "High Quality" to "جودة عالية",
    "Same Wi-Fi required" to "يجب استخدام شبكة Wi-Fi نفسها",
    "Keep this screen open and select this receiver from the sender phone." to "أبقِ هذه الشاشة مفتوحة واختر هذا المستقبل من هاتف الإرسال.",
    "Start a temporary local receiver page with WebRTC signaling." to "ابدأ صفحة استقبال محلية مؤقتة مع إشارات WebRTC.",
    "Ready when you are" to "جاهز عندما تكون مستعداً"
)

@Composable
fun A(text: String): String = if (LocalArabic.current) arabicTranslations[text] ?: text else text
