package com.carcast.mirror

import androidx.compose.runtime.Composable
import androidx.compose.runtime.compositionLocalOf

val LocalArabic = compositionLocalOf { false }

private val arabicTranslations = mapOf(
    "Cast" to "البث",
    "Cast screen" to "شاشة البث",
    "Receive" to "الاستقبال",
    "Browser" to "المتصفح",
    "Car" to "السيارة",
    "Help" to "المساعدة",
    "Settings" to "الإعدادات",
    "Diagnostics" to "التشخيص",
    "Confirm pairing code" to "تأكيد رمز الاقتران",
    "Pairing code" to "رمز الاقتران",
    "Continue" to "متابعة",
    "Cancel" to "إلغاء",
    "Local network access" to "الوصول إلى الشبكة المحلية",
    "Allow local network access" to "السماح بالوصول إلى الشبكة المحلية",
    "Nearby displays" to "الشاشات القريبة",
    "No displays found yet" to "لم يتم العثور على شاشات بعد",
    "Use Android System Cast" to "استخدام بث نظام Android",
    "Browser receiver" to "مستقبل المتصفح",
    "Start Browser Receiver" to "بدء مستقبل المتصفح",
    "Stop Casting" to "إيقاف البث",
    "Reconnect" to "إعادة الاتصال",
    "Approve this TV connection" to "الموافقة على اتصال التلفاز",
    "Approve & Start" to "موافقة وبدء",
    "Reject" to "رفض",
    "Open on your TV" to "افتح على التلفاز",
    "Car mode" to "وضع السيارة",
    "Help & FAQ" to "المساعدة والأسئلة الشائعة",
    "Privacy" to "الخصوصية",
    "Privacy options" to "خيارات الخصوصية",
    "Advertising" to "الإعلانات",
    "Language" to "اللغة",
    "English" to "الإنجليزية",
    "Arabic" to "العربية",
    "Arabic language" to "اللغة العربية",
    "Diagnostics" to "التشخيص",
    "Connection" to "الاتصال",
    "Video" to "الفيديو",
    "Network" to "الشبكة",
    "Audio" to "الصوت",
    "Manual receiver" to "مستقبل يدوي",
    "IP address" to "عنوان IP",
    "Port" to "المنفذ",
    "Start receiver" to "بدء المستقبل",
    "Stop receiver" to "إيقاف المستقبل",
    "CONNECT" to "اتصال",
    "DECLINE" to "رفض",
    "CLEAR" to "مسح",
    "COPY DEBUG REPORT" to "نسخ تقرير التشخيص",
    "What will be shared" to "ما سيتم مشاركته",
    "Share device audio" to "مشاركة صوت الجهاز",
    "Actual stream" to "البث الفعلي",
    "Supported paths" to "المسارات المدعومة",
    "Why can’t I see a receiver?" to "لماذا لا أرى مستقبلاً؟",
    "Why is audio unavailable?" to "لماذا الصوت غير متاح؟",
    "How do I recover a failed session?" to "كيف أستعيد جلسة فاشلة؟",
    "What does CarCast store?" to "ماذا يخزن CarCast؟",
    "Cast screen" to "شاشة البث",
    "Find your display" to "ابحث عن شاشتك",
    "Securely mirror to a nearby screen on your local network." to "اعكس الشاشة بأمان إلى شاشة قريبة على شبكتك المحلية.",
    "PERMISSION NEEDED" to "الإذن مطلوب",
    "CarCast needs local network access to discover and securely connect to a receiver. Screen content is not uploaded." to "يحتاج CarCast إلى الوصول للشبكة المحلية للعثور على مستقبل والاتصال به بأمان. لا يتم رفع محتوى الشاشة.",
    "Scan again" to "إعادة الفحص",
    "Scan for displays" to "البحث عن الشاشات",
    "Keep this screen open while CarCast checks your local network. You can also connect by IP or use Android System Cast." to "أبقِ هذه الشاشة مفتوحة أثناء فحص CarCast لشبكتك المحلية. يمكنك أيضاً الاتصال بعنوان IP أو استخدام بث نظام Android.",
    "SCANNING" to "جارٍ الفحص",
    "FOUND" to "تم العثور",
    "TV" to "تلفاز",
    "CarCast Receiver" to "مستقبل CarCast",
    "APPROVAL REQUIRED" to "الموافقة مطلوبة",
    "Confirm that both screens show the same verification code:" to "تأكد من ظهور رمز التحقق نفسه على الشاشتين:",
    "Connected · " to "متصل · ",
    "STARTING" to "جارٍ البدء",
    "Starting Browser Receiver…" to "جارٍ بدء مستقبل المتصفح…",
    "Starting…" to "جارٍ البدء…",
    "NEEDS ATTENTION" to "يتطلب الانتباه",
    "ACTION REQUIRED" to "إجراء مطلوب",
    "Browser session" to "جلسة المتصفح",
    "Quality: " to "الجودة: ",
    "Waiting for browser" to "بانتظار المتصفح",
    "Send supported phone audio to the receiver." to "إرسال صوت الهاتف المدعوم إلى المستقبل.",
    "Stop Receiver" to "إيقاف المستقبل",
    "COMPATIBILITY NOTE" to "ملاحظة التوافق",
    "Browser receiver debug" to "تشخيص مستقبل المتصفح",
    "Last successful stage" to "آخر مرحلة ناجحة",
    "Last error stage" to "آخر مرحلة بها خطأ",
    "Exception" to "الاستثناء",
    "Message" to "الرسالة",
    "Unavailable" to "غير متاح",
    "None" to "لا يوجد",
    "LOCAL" to "محلي",
    "SECURE LOCAL CASTING" to "البث المحلي الآمن",
    "CarCast Debug Report" to "تقرير تشخيص CarCast",
    "Enter the temporary six-digit code shown on the receiver." to "أدخل الرمز المؤقت المكوّن من ستة أرقام الظاهر على المستقبل.",

    "Ready to receive from a nearby CarCast phone." to "جاهز للاستقبال من هاتف CarCast قريب.",
    "Stream to a TV or computer browser over your local network." to "بث إلى تلفاز أو متصفح كمبيوتر عبر شبكتك المحلية.",
    "Understand which in-vehicle paths CarCast supports." to "تعرّف على طرق الاستخدام التي يدعمها CarCast داخل المركبة.",
    "Private, local casting with clear recovery steps." to "بث محلي وخاص مع خطوات واضحة للاستعادة.",
    "Manage privacy choices without changing your casting setup." to "إدارة خيارات الخصوصية دون تغيير إعدادات البث.",
    "Session health and browser receiver troubleshooting." to "حالة الجلسة واستكشاف أخطاء مستقبل المتصفح وإصلاحها.",
    "Auto" to "تلقائي",
    "Smooth" to "سلس",
    "High Quality" to "جودة عالية",
    "Same Wi-Fi required" to "يجب استخدام شبكة Wi-Fi نفسها",
    "Keep this screen open and select this receiver from the sender phone." to "أبقِ هذه الشاشة مفتوحة واختر هذا المستقبل من هاتف الإرسال.",
    "Start a temporary local receiver page with WebRTC signaling." to "ابدأ صفحة استقبال محلية مؤقتة مع إشارات WebRTC.",
    "Ready when you are" to "جاهز عندما تكون مستعداً"
)

@Composable
fun A(text: String): String = if (LocalArabic.current) arabicTranslations[text] ?: text else text
